In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('train.txt',sep=';',header=None,names=['text','emotions'])

In [3]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
emotions = df['emotions'].unique()

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
df['emotions'] =le.fit_transform(df['emotions'])

In [8]:
df

                                                    text  emotions
0                                i didnt feel humiliated         4
1      i can go from feeling so hopeless to so damned...         4
2       im grabbing a minute to post i feel greedy wrong         0
3      i am ever feeling nostalgic about the fireplac...         3
4                                   i am feeling grouchy         0
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         4
15996  i am now turning and i feel pathetic that i am...         4
15997                     i feel strong and good overall         2
15998  i feel like this was such a rude comment and i...         0
15999  i know a lot but i feel so stupid because i ca...         4

[16000 rows x 2 columns]

In [9]:
df

                                                    text  emotions
0                                i didnt feel humiliated         4
1      i can go from feeling so hopeless to so damned...         4
2       im grabbing a minute to post i feel greedy wrong         0
3      i am ever feeling nostalgic about the fireplac...         3
4                                   i am feeling grouchy         0
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         4
15996  i am now turning and i feel pathetic that i am...         4
15997                     i feel strong and good overall         2
15998  i feel like this was such a rude comment and i...         0
15999  i know a lot but i feel so stupid because i ca...         4

[16000 rows x 2 columns]

In [10]:
import string
# translator = str.maketrans('', '', string.punctuation)
marks = string.punctuation

In [11]:
marks

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [12]:
def remove_punc(text):
    for char in marks:
        text= text.replace(char,'')
    return text

In [14]:
df['text']=df['text'].apply(remove_punc)

In [15]:
df

                                                    text  emotions
0                                i didnt feel humiliated         4
1      i can go from feeling so hopeless to so damned...         4
2       im grabbing a minute to post i feel greedy wrong         0
3      i am ever feeling nostalgic about the fireplac...         3
4                                   i am feeling grouchy         0
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         4
15996  i am now turning and i feel pathetic that i am...         4
15997                     i feel strong and good overall         2
15998  i feel like this was such a rude comment and i...         0
15999  i know a lot but i feel so stupid because i ca...         4

[16000 rows x 2 columns]